In [252]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [253]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [254]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [255]:
df.shape

(569, 33)

In [256]:
df = df.drop(columns=['id','Unnamed: 32'])

In [257]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [258]:
df.shape

(569, 31)

In [259]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [260]:
type(y)

pandas.Series

In [261]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [262]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
460,17.080,27.15,111.20,930.9,0.09898,0.11100,0.10070,0.06431,0.1793,0.06281,...,22.96,34.49,152.10,1648.0,0.1600,0.24440,0.26390,0.15550,0.3010,0.09060
42,19.070,24.81,128.30,1104.0,0.09081,0.21900,0.21070,0.09961,0.2310,0.06343,...,24.09,33.17,177.40,1651.0,0.1247,0.74440,0.72420,0.24930,0.4670,0.10380
529,12.070,13.44,77.83,445.2,0.11000,0.09009,0.03781,0.02798,0.1657,0.06608,...,13.45,15.77,86.92,549.9,0.1521,0.16320,0.16220,0.07393,0.2781,0.08052
275,11.890,17.36,76.20,435.6,0.12250,0.07210,0.05929,0.07404,0.2015,0.05875,...,12.40,18.99,79.46,472.4,0.1359,0.08368,0.07153,0.08946,0.2220,0.06033
117,14.870,16.67,98.64,682.5,0.11620,0.16490,0.16900,0.08923,0.2157,0.06768,...,18.81,27.37,127.10,1095.0,0.1878,0.44800,0.47040,0.20270,0.3585,0.10650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
444,18.030,16.85,117.50,990.0,0.08947,0.12320,0.10900,0.06254,0.1720,0.05780,...,20.38,22.02,133.30,1292.0,0.1263,0.26660,0.42900,0.15350,0.2842,0.08225
352,25.730,17.46,174.20,2010.0,0.11490,0.23630,0.33680,0.19130,0.1956,0.06121,...,33.13,23.58,229.30,3234.0,0.1530,0.59370,0.64510,0.27560,0.3690,0.08815
263,15.610,19.38,100.00,758.6,0.07840,0.05616,0.04209,0.02847,0.1547,0.05443,...,17.91,31.67,115.90,988.6,0.1084,0.18070,0.22600,0.08568,0.2683,0.06829
273,9.742,15.67,61.50,289.9,0.09037,0.04689,0.01103,0.01407,0.2081,0.06312,...,10.75,20.88,68.09,355.2,0.1467,0.09370,0.04043,0.05159,0.2841,0.08175
132,16.160,21.54,106.20,809.8,0.10080,0.12840,0.10430,0.05613,0.2160,0.05891,...,19.47,31.68,129.70,1175.0,0.1395,0.30550,0.29920,0.13120,0.3480,0.07619

In [263]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [264]:
X_train

array([[ 0.86349976,  1.92034448,  0.81469499, ...,  0.60849735,
         0.1715382 ,  0.3210215 ],
       [ 1.43997696,  1.3654955 ,  1.53277315, ...,  2.03329435,
         2.82455649,  1.0236527 ],
       [-0.5878323 , -1.3305015 , -0.58660723, ..., -0.63052921,
        -0.19445047, -0.21553323],
       ...,
       [ 0.43765981,  0.07796131,  0.3443748 , ..., -0.45204984,
        -0.35107444, -0.86653168],
       [-1.26222372, -0.80173516, -1.27235088, ..., -0.96986786,
        -0.09855824, -0.15006078],
       [ 0.59698768,  0.59012961,  0.60473062, ...,  0.23938683,
         0.92269398, -0.44601755]], shape=(455, 30))

In [265]:
y_train

460    M
42     M
529    B
275    B
117    M
      ..
444    M
352    M
263    M
273    B
132    M
Name: diagnosis, Length: 455, dtype: str

In [266]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [267]:
y_train

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1])

In [268]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [269]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [270]:
# class MySimpleNN():
#     def __init__(self, X):
#         self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#         self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

#     def forward(self, X):
#         z = torch.matmul(X, self.weights) + self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred

#     def loss_function(self, y_pred, y):

#         # clamp prediction to avoid log(0)
#         epsilon = 1e-7
#         y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

#         # calculate loss
#         loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
#         return loss

## Using nn Module

In [271]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [272]:
learning_rate = 0.1
epochs = 25

# define loss function
loss_function = nn.BCELoss()

In [273]:
# # create model
# model = MySimpleNN(X_train_tensor)

# # define loop
# for epoch in range(epochs):

#     # forward pass
#     y_pred = model.forward(X_train_tensor)

#     # loss calculate
#     loss = model.loss_function(y_pred, y_train_tensor)

#     # backward pass
#     loss.backward()

#     #parameter update
#     with torch.no_grad():
#         model.weights -= learning_rate * model.weights.grad
#         model.bias -= learning_rate * model.bias.grad

#     # zero gradients
#     model.weights.grad.zero_()
#     model.bias.grad.zero_()

#     # print loss in each epoch
#     print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

In [274]:
X_train_tensor.shape[1]

30

In [275]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [276]:
# create model
model = MySimpleNN(num_features=X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    #parameter update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6806942820549011
Epoch: 2, Loss: 0.5118717551231384
Epoch: 3, Loss: 0.4230736494064331
Epoch: 4, Loss: 0.37002724409103394
Epoch: 5, Loss: 0.33405226469039917
Epoch: 6, Loss: 0.3075951933860779
Epoch: 7, Loss: 0.2870824933052063
Epoch: 8, Loss: 0.2705762982368469
Epoch: 9, Loss: 0.25692132115364075
Epoch: 10, Loss: 0.24538017809391022
Epoch: 11, Loss: 0.23545730113983154
Epoch: 12, Loss: 0.22680573165416718
Epoch: 13, Loss: 0.2191745638847351
Epoch: 14, Loss: 0.21237720549106598
Epoch: 15, Loss: 0.20627166330814362
Epoch: 16, Loss: 0.20074772834777832
Epoch: 17, Loss: 0.1957184225320816
Epoch: 18, Loss: 0.19111394882202148
Epoch: 19, Loss: 0.18687768280506134
Epoch: 20, Loss: 0.1829630583524704
Epoch: 21, Loss: 0.17933134734630585
Epoch: 22, Loss: 0.17595015466213226
Epoch: 23, Loss: 0.1727920025587082
Epoch: 24, Loss: 0.16983354091644287
Epoch: 25, Loss: 0.1670546531677246

In [277]:
# model.weights
model.linear.weight

Parameter containing:
tensor([[ 0.2539,  0.1492,  0.3475,  0.2758,  0.1479,  0.2843,  0.0321,  0.1170,
         -0.0416, -0.0338,  0.2081, -0.0502,  0.1635,  0.0463, -0.1227,  0.0811,
         -0.1106,  0.0696, -0.0679,  0.0618,  0.3583,  0.2265,  0.4195,  0.0895,
          0.2578,  0.2926,  0.2133,  0.0978,  0.2985,  0.0216]],
       requires_grad=True)

In [278]:
# model.bias
model.linear.bias

Parameter containing:
tensor([-0.2185], requires_grad=True)

In [279]:
# model evaluation
with torch.no_grad():
    # y_pred = model.forward(X_test_tensor)
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

print(y_pred)

Accuracy: 0.5346260666847229
tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.]])