In [46]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [47]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [48]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [49]:
df.shape

(569, 33)

In [50]:
df = df.drop(columns=['id','Unnamed: 32'])

In [51]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [52]:
df.shape

(569, 31)

In [53]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [54]:
type(y)

pandas.Series

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [56]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
61,8.598,20.98,54.66,221.8,0.12430,0.08963,0.03000,0.009259,0.1828,0.06757,...,9.565,27.04,62.06,273.9,0.1639,0.16980,0.09001,0.02778,0.2972,0.07712
275,11.890,17.36,76.20,435.6,0.12250,0.07210,0.05929,0.074040,0.2015,0.05875,...,12.400,18.99,79.46,472.4,0.1359,0.08368,0.07153,0.08946,0.2220,0.06033
513,14.580,13.66,94.29,658.8,0.09832,0.08918,0.08222,0.043490,0.1739,0.05640,...,16.760,17.24,108.50,862.0,0.1223,0.19280,0.24920,0.09186,0.2626,0.07048
404,12.340,14.95,78.29,469.1,0.08682,0.04571,0.02109,0.020540,0.1571,0.05708,...,13.180,16.85,84.11,533.1,0.1048,0.06744,0.04921,0.04793,0.2298,0.05974
135,12.770,22.47,81.72,506.3,0.09055,0.05761,0.04711,0.027040,0.1585,0.06065,...,14.490,33.37,92.04,653.6,0.1419,0.15230,0.21770,0.09331,0.2829,0.08067
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,9.667,18.49,61.49,289.1,0.08946,0.06258,0.02948,0.015140,0.2238,0.06413,...,11.140,25.62,70.88,385.2,0.1234,0.15420,0.12770,0.06560,0.3174,0.08524
311,14.610,15.69,92.68,664.9,0.07618,0.03515,0.01447,0.018770,0.1632,0.05255,...,16.460,21.75,103.70,840.8,0.1011,0.07087,0.04746,0.05813,0.2530,0.05695
322,12.860,13.32,82.82,504.8,0.11340,0.08834,0.03800,0.034000,0.1543,0.06476,...,14.040,21.08,92.80,599.5,0.1547,0.22310,0.17910,0.11550,0.2382,0.08553
516,18.310,20.58,120.80,1052.0,0.10680,0.12480,0.15690,0.094510,0.1860,0.05941,...,21.860,26.20,142.20,1493.0,0.1492,0.25360,0.37590,0.15100,0.3074,0.07863
39,13.480,20.82,88.40,559.2,0.10160,0.12550,0.10630,0.054390,0.1720,0.06419,...,15.530,26.02,107.30,740.4,0.1610,0.42250,0.50300,0.22580,0.2807,0.10710

In [57]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
X_train

array([[-1.57324168,  0.40910278, -1.53845774, ..., -1.31014327,
         0.14264784, -0.35595525],
       [-0.65389942, -0.42753097, -0.66598588, ..., -0.37962249,
        -1.11663089, -1.31684285],
       [ 0.09732497, -1.28265385,  0.06674467, ..., -0.34341546,
        -0.43675434, -0.73596083],
       ...,
       [-0.38301181, -1.36123271, -0.39784457, ...,  0.01322382,
        -0.8453501 ,  0.125347  ],
       [ 1.13898556,  0.31665706,  1.14052504, ...,  0.5487862 ,
         0.31345426, -0.26953832],
       [-0.20986716,  0.37212449, -0.17182818, ...,  1.67723876,
        -0.13365667,  1.35979284]], shape=(455, 30))

In [59]:
y_train

61     B
275    B
513    B
404    B
135    M
      ..
470    B
311    B
322    B
516    M
39     M
Name: diagnosis, Length: 455, dtype: str

In [60]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [61]:
y_train

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1])

In [62]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [63]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [64]:
class MySimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self, y_pred, y):

        # clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [65]:
learning_rate = 0.1
epochs = 25

In [66]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

    # forward pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    #parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.639359913508661
Epoch: 2, Loss: 3.502196342433195
Epoch: 3, Loss: 3.3638404941439455
Epoch: 4, Loss: 3.219570708582081
Epoch: 5, Loss: 3.0703219732670837
Epoch: 6, Loss: 2.9167526955658953
Epoch: 7, Loss: 2.7588391676059945
Epoch: 8, Loss: 2.5945095184269356
Epoch: 9, Loss: 2.4272512925061625
Epoch: 10, Loss: 2.26301137261565
Epoch: 11, Loss: 2.094154661625933
Epoch: 12, Loss: 1.928588034718193
Epoch: 13, Loss: 1.7673307986396074
Epoch: 14, Loss: 1.6127832535541498
Epoch: 15, Loss: 1.4683018798993175
Epoch: 16, Loss: 1.3346563247442786
Epoch: 17, Loss: 1.216264469068911
Epoch: 18, Loss: 1.114302190581363
Epoch: 19, Loss: 1.0291922794056916
Epoch: 20, Loss: 0.9603289636778777
Epoch: 21, Loss: 0.9060002477720225
Epoch: 22, Loss: 0.8637257989172964
Epoch: 23, Loss: 0.8309024806771848
Epoch: 24, Loss: 0.8052809479074681
Epoch: 25, Loss: 0.7850976948325175

In [68]:
model.weights

tensor([[-0.1632],
        [ 0.2370],
        [ 0.0888],
        [ 0.2557],
        [-0.0074],
        [-0.6468],
        [ 0.1056],
        [-0.4201],
        [ 0.2328],
        [ 0.5652],
        [ 0.1388],
        [ 0.2298],
        [ 0.1550],
        [-0.1822],
        [-0.1684],
        [ 0.1619],
        [ 0.0708],
        [-0.4126],
        [ 0.2882],
        [-0.0344],
        [-0.1799],
        [-0.1654],
        [ 0.3902],
        [-0.2062],
        [ 0.3017],
        [-0.0097],
        [ 0.3094],
        [ 0.2136],
        [ 0.2534],
        [-0.0843]], dtype=torch.float64, requires_grad=True)

In [69]:
model.bias

tensor([-0.1433], dtype=torch.float64, requires_grad=True)

In [72]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

print(y_pred)

Accuracy: 0.5138503909111023
tensor([[0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.]])