In [34]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [35]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [36]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [37]:
df.shape

(569, 33)

In [38]:
df = df.drop(columns=['id','Unnamed: 32'])

In [39]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
df.shape

(569, 31)

In [41]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [42]:
type(y)

pandas.Series

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y)

In [44]:
X_train

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
108,22.270,19.67,152.80,1509.0,0.13260,0.27680,0.42640,0.18230,0.2556,0.07039,...,28.40,28.01,206.80,2360.0,0.1701,0.69970,0.96080,0.29100,0.4055,0.09789
139,11.280,13.39,73.00,384.8,0.11640,0.11360,0.04635,0.04796,0.1771,0.06072,...,11.92,15.77,76.53,434.0,0.1367,0.18220,0.08669,0.08611,0.2102,0.06784
264,17.190,22.07,111.60,928.3,0.09726,0.08995,0.09061,0.06527,0.1867,0.05580,...,21.58,29.33,140.50,1436.0,0.1558,0.25670,0.38890,0.19840,0.3216,0.07570
156,17.680,20.74,117.40,963.7,0.11150,0.16650,0.18550,0.10540,0.1971,0.06166,...,20.47,25.11,132.90,1302.0,0.1418,0.34980,0.35830,0.15150,0.2463,0.07738
331,12.980,19.35,84.52,514.0,0.09579,0.11250,0.07107,0.02950,0.1761,0.06540,...,14.42,21.95,99.21,634.3,0.1288,0.32530,0.34390,0.09858,0.3596,0.09166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,17.570,15.05,115.00,955.1,0.09847,0.11570,0.09875,0.07953,0.1739,0.06149,...,20.01,19.52,134.90,1227.0,0.1255,0.28120,0.24890,0.14560,0.2756,0.07919
299,10.510,23.09,66.85,334.2,0.10150,0.06797,0.02495,0.01875,0.1695,0.06556,...,10.93,24.22,70.10,362.7,0.1143,0.08614,0.04158,0.03125,0.2227,0.06777
103,9.876,19.40,63.95,298.3,0.10050,0.09697,0.06154,0.03029,0.1945,0.06322,...,10.76,26.83,72.22,361.2,0.1559,0.23020,0.26440,0.09749,0.2622,0.08490
122,24.250,20.20,166.20,1761.0,0.14470,0.28670,0.42680,0.20120,0.2655,0.06877,...,26.02,23.99,180.90,2073.0,0.1696,0.42440,0.58030,0.22480,0.3222,0.08009
216,11.890,18.35,77.32,432.2,0.09363,0.11540,0.06636,0.03142,0.1967,0.06314,...,13.25,27.10,86.20,531.2,0.1405,0.30460,0.28060,0.11380,0.3397,0.08365

In [45]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [46]:
X_train

array([[ 2.31353977,  0.1287521 ,  2.49765427, ...,  2.6809391 ,
         1.92165262,  0.73940671],
       [-0.80897351, -1.35499967, -0.78038543, ..., -0.43092453,
        -1.3154049 , -0.90423422],
       [ 0.87019424,  0.69579099,  0.80523277, ...,  1.27453287,
         0.5310273 , -0.47431683],
       ...,
       [-1.20788239,  0.06496022, -1.15214307, ..., -0.25808541,
        -0.45351554,  0.02889437],
       [ 2.87610358,  0.25397319,  3.04810204, ...,  1.67549534,
         0.54097218, -0.23419757],
       [-0.63565839, -0.18311929, -0.60292764, ..., -0.01036958,
         0.83103109, -0.03947671]], shape=(455, 30))

In [47]:
y_train

108    M
139    B
264    M
156    M
331    B
      ..
29     M
299    B
103    B
122    M
216    B
Name: diagnosis, Length: 455, dtype: str

In [48]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [49]:
y_train

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0])

In [50]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [51]:
X_train_tensor.shape

torch.Size([455, 30])

### Using Dataset and DataLoader

In [52]:
from torch.utils.data import Dataset, DataLoader

class CustomDataSet(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]

In [53]:
train_dataset = CustomDataSet(X_train_tensor, y_train_tensor)
test_dataset = CustomDataSet(X_test_tensor, y_test_tensor)

In [54]:
train_dataset[10]

(tensor([-0.3203,  1.4188, -0.3856, -0.3802, -0.9134, -1.0092, -0.9536, -0.7960,
         -0.5169, -1.1998, -0.4961,  0.0484, -0.5744, -0.4032, -0.3305, -0.9221,
         -0.8958, -0.8766, -1.0342, -0.8732, -0.3996,  1.0370, -0.4836, -0.4423,
         -0.4813, -0.9179, -1.1060, -0.8395, -0.9773, -1.1739]),
 tensor(0.))

In [55]:
train_dataloader = DataLoader(dataset=train_dataset, batch_size=32, shuffle=True)
test_dataloader = DataLoader(dataset=test_dataset, batch_size=32, shuffle=True)

In [73]:
train_dataloader.dataset.features

tensor([[ 2.3135,  0.1288,  2.4977,  ...,  2.6809,  1.9217,  0.7394],
        [-0.8090, -1.3550, -0.7804,  ..., -0.4309, -1.3154, -0.9042],
        [ 0.8702,  0.6958,  0.8052,  ...,  1.2745,  0.5310, -0.4743],
        ...,
        [-1.2079,  0.0650, -1.1521,  ..., -0.2581, -0.4535,  0.0289],
        [ 2.8761,  0.2540,  3.0481,  ...,  1.6755,  0.5410, -0.2342],
        [-0.6357, -0.1831, -0.6029,  ..., -0.0104,  0.8310, -0.0395]])

## Defining the model

## Using nn Module

In [56]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()

        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [57]:
learning_rate = 0.1
epochs = 25

In [58]:
# create model
model = MySimpleNN(num_features=X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [59]:
X_train_tensor.shape[1]

30

In [60]:
type(loss_function)

torch.nn.modules.loss.BCELoss

### Training Pipeline

In [68]:
# define loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_dataloader:
        # forward pass
        y_pred = model(batch_features)

        # loss calculate
        loss = loss_function(y_pred, batch_labels.view(-1,1))

        # clear gradients
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        #parameter update
        optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.3160289227962494
Epoch: 2, Loss: 0.0024643626529723406
Epoch: 3, Loss: 0.448662132024765
Epoch: 4, Loss: 0.044279586523771286
Epoch: 5, Loss: 0.015223660506308079
Epoch: 6, Loss: 0.02769375406205654
Epoch: 7, Loss: 0.7837767004966736
Epoch: 8, Loss: 0.02932441048324108
Epoch: 9, Loss: 0.7779211401939392
Epoch: 10, Loss: 0.007377252914011478
Epoch: 11, Loss: 0.11670850962400436
Epoch: 12, Loss: 0.03472019359469414
Epoch: 13, Loss: 0.08986668288707733
Epoch: 14, Loss: 0.04660215973854065
Epoch: 15, Loss: 0.041885651648044586
Epoch: 16, Loss: 0.7767553329467773
Epoch: 17, Loss: 0.07437455654144287
Epoch: 18, Loss: 0.027907300740480423
Epoch: 19, Loss: 0.03195498511195183
Epoch: 20, Loss: 0.03021634928882122
Epoch: 21, Loss: 0.7687589526176453
Epoch: 22, Loss: 0.004487510304898024
Epoch: 23, Loss: 0.030650688335299492
Epoch: 24, Loss: 0.026069773361086845
Epoch: 25, Loss: 0.03556468337774277

In [62]:
# model.weights
model.linear.weight

Parameter containing:
tensor([[ 0.4215,  0.6404,  0.5975,  0.5229,  0.2499,  0.0948,  0.4073,  0.5720,
          0.1167, -0.3597,  0.3464,  0.0298,  0.5462,  0.3868,  0.0052, -0.2627,
         -0.0446,  0.0703, -0.1927, -0.2992,  0.7294,  0.6664,  0.8058,  0.5306,
          0.5944,  0.0829,  0.5272,  0.5023,  0.4605,  0.0492]],
       requires_grad=True)

In [63]:
# model.bias
model.linear.bias

Parameter containing:
tensor([-0.4728], requires_grad=True)

### Evaluation

In [64]:
# model evaluation using test_dataloader
model.eval()  # set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_dataloader:
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()

        # calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

print(y_pred)

Accuracy: 0.9844
tensor([[1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.]])