# K Nearest Neighbour

- Step 1: Choose K (K=3)
- Step 2: Calculate Distance between new point and all training data points
- Step 3: Select Nearest Neighbours
- Step 4: Majority Voting (Male=2, Female=1)
- Step 5: Prediction:Male

- Choose K(3)
- FInd 3 nearest houses (1000, 1200, 1300)
- Average  Output (175/3 = 58.33 lakhs)

### Distance Metrics

- Euclidean Distance - st.line distance (airplane route, bird flight path)
- Manhattan Distance -

In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [38]:
df = pd.read_csv('StudentsPerformance.csv')

In [39]:
df.head()

   gender race/ethnicity  ... reading score writing score
0  female        group B  ...            72            74
1  female        group C  ...            90            88
2  female        group B  ...            95            93
3    male        group A  ...            57            44
4    male        group C  ...            78            75

[5 rows x 8 columns]

In [40]:
df['average_score'] = (df['math score'] + df['reading score'] + df['writing score'])

In [41]:
df.head()

   gender race/ethnicity  ... writing score average_score
0  female        group B  ...            74           218
1  female        group C  ...            88           247
2  female        group B  ...            93           278
3    male        group A  ...            44           148
4    male        group C  ...            75           229

[5 rows x 9 columns]

In [42]:
X = df.drop(columns=['math score','reading score','writing score','average_score'])

In [43]:
X.head()

   gender race/ethnicity  ...         lunch test preparation course
0  female        group B  ...      standard                    none
1  female        group C  ...      standard               completed
2  female        group B  ...      standard                    none
3    male        group A  ...  free/reduced                    none
4    male        group C  ...      standard                    none

[5 rows x 5 columns]

In [44]:
y = df[['average_score']]

In [45]:
y

     average_score
0              218
1              247
2              278
3              148
4              229
..             ...
995            282
996            172
997            195
998            223
999            249

[1000 rows x 1 columns]

In [46]:
type(y)

pandas.DataFrame

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [48]:
categorical_features = X.columns.tolist()
categorical_features

['gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course']

In [49]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'cat',
            OneHotEncoder(
                drop='first',
                handle_unknown='ignore'
            ),
            categorical_features
        )
    ]
)

In [50]:
pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('scaler', StandardScaler(with_mean=False)),
        ('knn', KNeighborsRegressor())
    ]
)

In [51]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['gender', 'race/ethnicity',
                                                   'parental level of '
                                                   'education',
                                                   'lunch',
                                                   'test preparation '
                                                   'course'])])),
                ('scaler', StandardScaler(with_mean=False)),
                ('knn', KNeighborsRegressor())])

In [52]:
y_pred = pipeline.predict(X_test)

In [53]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [54]:
print(mae)
print(rmse)
print(r2)

35.86
46.19933765758985
-0.10629751498873352

In [55]:
param_grid = {
    'knn__n_neighbors': [3, 5, 7, 9, 11, 15],
    'knn__weights': ['uniform', 'distance'],
    'knn__metric': ['euclidean', 'manhattan', 'minkowski'],
    'knn__p': [1, 2],                    # only used when metric='minkowski'
    'knn__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'knn__leaf_size': [20, 30, 40]       # only affects ball_tree and kd_tree
}

In [56]:
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

In [57]:
from sklearn.metrics import get_scorer_names
print(sorted(get_scorer_names()))

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'd2_absolute_error_score', 'd2_brier_score', 'd2_log_loss_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'matthews_corrcoef', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_max_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_negative_likelihood_ratio', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'normalized_mutual_info_score', 'positive_likelihood_ratio', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'rand_score', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weighted', 'roc_auc_ovr', 'roc_auc_ovr_weighted', 'top_k_accuracy', 'v_measure_score']

In [58]:
grid = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='r2'
)

grid.fit(X_train, y_train)

/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")
/Users/nayan/ml/.venv/lib/python3.13/site-packages/sklearn/neighbors/_base.py:591: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: using brute force")

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('cat',
                                                                         OneHotEncoder(drop='first',
                                                                                       handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'race/ethnicity',
                                                                          'parental '
                                                                          'level '
                                                                          'of '
                                                                          'education',
                                                                          'lunch',
                                                                          'test '
                                                                          'preparation '
                                                                          'course'])])),
                                       ('scaler',
                                        StandardScaler(with_mean=False)),
                                       ('knn', KNeighborsRegressor())]),
             param_grid={'knn__algorithm': ['auto', 'ball_tree', 'kd_tree',
                                            'brute'],
                         'knn__leaf_size': [20, 30, 40],
                         'knn__metric': ['euclidean', 'manhattan', 'minkowski'],
                         'knn__n_neighbors': [3, 5, 7, 9, 11, 15],
                         'knn__p': [1, 2],
                         'knn__weights': ['uniform', 'distance']},
             scoring='r2')

In [61]:
results = pd.DataFrame(grid.cv_results_)

In [62]:
results[['params','mean_test_score','std_test_score','rank_test_score']].sort_values('rank_test_score').head(10)

                                                params  ...  rank_test_score
260  {'knn__algorithm': 'ball_tree', 'knn__leaf_siz...  ...                1
500  {'knn__algorithm': 'kd_tree', 'knn__leaf_size'...  ...                1
68   {'knn__algorithm': 'auto', 'knn__leaf_size': 2...  ...                1
838  {'knn__algorithm': 'brute', 'knn__leaf_size': ...  ...                1
550  {'knn__algorithm': 'kd_tree', 'knn__leaf_size'...  ...                1
284  {'knn__algorithm': 'ball_tree', 'knn__leaf_siz...  ...                1
188  {'knn__algorithm': 'auto', 'knn__leaf_size': 4...  ...                1
836  {'knn__algorithm': 'brute', 'knn__leaf_size': ...  ...                1
406  {'knn__algorithm': 'ball_tree', 'knn__leaf_siz...  ...                1
190  {'knn__algorithm': 'auto', 'knn__leaf_size': 4...  ...                1

[10 rows x 4 columns]

In [64]:
grid.best_params_

{'knn__algorithm': 'auto',
 'knn__leaf_size': 20,
 'knn__metric': 'manhattan',
 'knn__n_neighbors': 15,
 'knn__p': 1,
 'knn__weights': 'uniform'}

In [65]:
grid.best_score_

np.float64(0.1392228115349262)